config/routes.rb
Sample::Application.routes.draw do

  get "users/new"

 match "/about",:to =>"pages#about"
 match "/contact",:to =>"pages#contact"
 match "/help",:to =>"pages#help"
 match "/signup",:to =>"users#new"
 

 root :to => "pages#home"
 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
	  @title = "Home"
  end

  def about
	  @title = "About"
  end

  def contact
	  @title = "Contact"

  end

  def help
	  @title = "Help"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
	  @title = "Sign up"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>RoR Sample App | <%=@title%></title>
  <%=stylesheet_link_tag 'blueprint/screen',:media => 'screen'%>
  <%=stylesheet_link_tag 'blueprint/print',:media => 'print'%>
  <%=stylesheet_link_tag 'custom',:media => 'screen'%>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div class = "container">	
	<header>
		<%=image_tag "#",:size =>'50x50'%>
		<nav>
			<ul>
			<li><%=link_to "Home",root_path %></li>
			<li><%=link_to "Help",help_path %></li>
			<li><%=link_to "Sign in","#"%></li>
			</ul>
		</nav>
	</header>
<section>
<%= yield %>
</section>
<footer>
	<nav>
  <ul>
  	<li><%= link_to "About",about_path%></li>
  	<li><%= link_to "Contact",contact_path%></li>
  </ul>
  </nav>
</foooter>
</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
Pages#Help

app/views/pages/home.html.erb
<h1>Sample App</h1>
This is the home page for the sample app
<%=link_to "Sign up",signup_path%>
	

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>